### ISSUE TITLE
TypeError on Making Request

### ISSUE THREAD

**Issue by akash2408** [apple/app-store-server-library-python#107]
![token error](https://github.com/user-attachments/assets/2178d6ab-7582-4cbc-9036-0433632fda5b)

I am using Python 3.8.10. I am using the latest version app-store-server-library 1.4.0.
When I am trying to make a request I am getting this error.
for testing I am making test send notification 

send_notification = client.request_test_notification()

How to solve this? am I missing something ?

**Comment by alexanderjordanbaker** [comment]
@akash2408 Can you share how you construct your client, that seems unexpected
