### ISSUE TITLE
Can't receive CONSUMPTION_REQUEST notification.

### ISSUE THREAD

**Issue by ricky0603** [apple/app-store-server-library-python#110]
@alexanderjordanbaker  @izanger 

My App uses an auto-renewal subscription, and I've been using the CONSUMPTION_REQUEST event to track user refund requests. However, since yesterday ( last CONSUMPTION_REQUEST received timestamp: 1727277862, uuid: d602b617-41dd-4f29-a1ca-83e2a8f80304), I haven't received any CONSUMPTION_REQUEST notifications. Previously, I would receive several CONSUMPTION_REQUEST notifications daily. All other types of notifications are functioning normally and I haven't changed anything.  I believe there still are some users request a refund, but I can't receive CONSUMPTION_REQUEST. 

I have watched your WWDC24 video and checked Apple's documents, that auto-renewal subscription can receive CONSUMPTION_REQUEST.

Can you check that?

Thanks.

**Comment by alexanderjordanbaker** [comment]
@ricky0603 This does not appear to be an concern with the library, but with the underlying infrastructure. I would recommend filing a ticket in Feedback Assistant under the App Store Server Notifications type, with information, and it will be reviewed.

**Comment by ricky0603** [comment]
> @ricky0603 This does not appear to be an concern with the library, but with the underlying infrastructure. I would recommend filing a ticket in Feedback Assistant under the App Store Server Notifications type, with information, and it will be reviewed.

I have submitted a ticket in Feedback Assistant, and the ticket ID is FB15292339.  Could you please assist in asking the colleague responsible for this part to take a look as soon as possible? This is very important to me.
