### ISSUE TITLE
The status type in LastTransactionsItem doesn't match with document

### ISSUE THREAD

**Issue by shellfly** [apple/app-store-server-library-python#12]
From the document, the `status` field in the [`LastTransactionsItem`](https://developer.apple.com/documentation/appstoreserverapi/lasttransactionsitem) is the status of an auto-renewable subscription, but the type is VerificationStatus in the code.

https://github.com/apple/app-store-server-library-python/blob/29123bfdf673863c40153e8532f3a45ffb33c913/appstoreserverlibrary/models/LastTransactionsItem.py#L17C22-L17C40

**Comment by shellfly** [comment]
It seems there is already an MR for it #11

**Comment by rhutkovich** [comment]
^ bump. Just found this issue as well, it is definitely not supposed to be `VerficationStatus`

**Comment by alexanderjordanbaker** [comment]
Resolved in https://github.com/apple/app-store-server-library-python/pull/11 and in version 0.2.0
