### ISSUE TITLE
[Feature] Need an example for refund lookup API

### ISSUE THREAD

**Issue by CodeMasterYi** [apple/app-store-server-library-python#21]
relative API `GET https://api.storekit.itunes.apple.com/inApps/v2/refund/lookup/{transactionId}`

**Comment by alexanderjordanbaker** [comment]
`response = client.get_refund_history(transaction_id, None)`

**Comment by alexanderjordanbaker** [comment]
Are you saying we need an example in the README for this endpoint?

**Comment by CodeMasterYi** [comment]
> Are you saying we need an example in the README for this endpoint? https://github.com/apple/app-store-server-library-python#receipt-usage contains an example for the Get Transaction History endpoint, which is very similar

Actually, A Python API reference is appreciated.

**Comment by CodeMasterYi** [comment]
> `response = client.get_refund_history(transaction_id, None)`

What I need now.

**Comment by CodeMasterYi** [comment]
Guess that Building a `Python API reference` is in your road map. I will close this issue.
