### ISSUE TITLE
[Question] Why I cannot lookup all of the refund history of my app! NOT ONLY ONE CUSTOMER's that related to the provided transactionId.

### ISSUE THREAD

**Issue by CodeMasterYi** [apple/app-store-server-library-python#31]
I would like to know how can I lookup all of the refund history of my app.
Is there any way to do that?
`client.get_refund_history` only for one customer?

**Comment by alexanderjordanbaker** [comment]
The refund history endpoint only lookups up for one customer at a time. See https://developer.apple.com/documentation/appstoreserverapi/get_refund_history/ for more information
