### ISSUE TITLE
`AppTransaction.appAppleId` is `None `when requesting `get_notification_history` and that makes verify_and_decode_app_transaction failed with `VerificationException: Verification failed with status INVALID_APP_IDENTIFIER`

### ISSUE THREAD

**Issue by elonzh** [apple/app-store-server-library-python#47]
![image](https://github.com/apple/app-store-server-library-python/assets/8749411/49a80c14-9aeb-489b-8a83-ab68ea50820c)

```
...
  File "/home/elonzh/.cache/pypoetry/virtualenvs/unob-hX3-r8Vo-py3.10/lib/python3.10/site-packages/appstoreserverlibrary/signed_data_verifier.py", line 110, in verify_and_decode_app_transaction
    raise VerificationException(VerificationStatus.INVALID_APP_IDENTIFIER)
          │                     └ <enum 'VerificationStatus'>
          └ <class 'appstoreserverlibrary.signed_data_verifier.VerificationException'>
appstoreserverlibrary.signed_data_verifier.VerificationException: Verification failed with status INVALID_APP_IDENTIFIER
```

**Comment by alexanderjordanbaker** [comment]
Those aren’t app transactions, those are signed notifications

**Comment by alexanderjordanbaker** [comment]
You need to use verifier.verify_and_decode_notification not verify_and_decode_app_transaction

**Comment by elonzh** [comment]
@alexanderjordanbaker It works, thanks!

**Comment by alexanderjordanbaker** [comment]
AppTransaction is https://developer.apple.com/documentation/storekit/apptransaction
JWSTransaction https://developer.apple.com/documentation/appstoreservernotifications/jwstransaction

https://developer.apple.com/documentation/appstoreservernotifications/data has details on the meaning of the fields in the notification
