### ISSUE TITLE
Test notifications for production env fails

### ISSUE THREAD

**Issue by dreamwieber** [apple/app-store-server-library-python#51]
I realize that this is Beta, but I'm not seeing any reason in the code why we wouldn't be able to send a test notification request for the Production environment. We need to be able to test our server side stuff to make sure that production requests are handled correctly. However, when requesting test notifications with production as the environment, the calls fail with 401. 

Don't think this is a configuration issue, because everything works in Sandbox. 

Is there something I'm missing in the code that prevents calls to Production links? Or is this some other bug?

**Comment by alexanderjordanbaker** [comment]
Is the app you’re testing for released yet? Production endpoints don’t work until you have had a production release.

**Comment by dreamwieber** [comment]
Ah – well, that explains it. No, this is an app still in TestFlight and pre v1 release. Well, that saved me from spiraling on a goose chase, thank you. 

Sounds like maybe this is something covered elsewhere in some App Store connects docs perhaps? There's no reason our check for environment shouldn't work, but just wanted to quadruple check that when a production requests came through to our server it would be properly handled.

**Comment by dreamwieber** [comment]
(Other questions aside, marking as closed.)
