### ISSUE TITLE
extract_transaction_id_from_app_receipt problem

### ISSUE THREAD

**Issue by 3406836221qqcom** [apple/app-store-server-library-python#62]
If an order contains two transaction information, two transaction IDs will be generated, but this extract_transaction_id_from_app_receipt function can only parse out one ID, which will cause the transaction ID of the other order to be lost.

**Comment by alexanderjordanbaker** [comment]
The Get Transaction History endpoint will return a user’s whole history, so only one transaction id is generally needed. https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history
