### ISSUE TITLE
Support for App Store Server Notifications V2

### ISSUE THREAD

**Issue by vongrad** [apple/app-store-server-library-python#64]
Do you plan to add support for App Store Server Notifications V2, since V1 is deprecated?

**Comment by alexanderjordanbaker** [comment]
This library supports V2 notifications, not V1

**Comment by vongrad** [comment]
When I check the code, I saw this:
```
def request_test_notification(self) -> SendTestNotificationResponse:
        """
        Ask App Store Server Notifications to send a test notification to your server.
        https://developer.apple.com/documentation/appstoreserverapi/request_a_test_notification

        :return: A response that contains the test notification token.
        :throws APIException: If a response was returned indicating the request could not be processed
        """
        return self._make_request("/inApps/v1/notifications/test", "POST", {}, None, SendTestNotificationResponse)
```
its using the `/v1` in all occurrences where notification is mentioned, why is that?

**Comment by rkotzy** [comment]
That's the App Store Server API version you're referencing, not the server notification version.

**Comment by alexanderjordanbaker** [comment]
Each endpoint in the App Store Server API is given a version in case the endpoint is changed in the future. For this endpoint https://developer.apple.com/documentation/appstoreserverapi/request_a_test_notification, the current endpoint version is V1. For example, Get Refund History https://developer.apple.com/documentation/appstoreserverapi/get_refund_history currently has a V2 as this was updated to include a new parameter, revision, unlike the now deprecated V1. This versioning, however, is per endpoint and not correlated with App Store Server Notification version.

**Comment by vongrad** [comment]
I understand now, thank you for the explanation!
