### ISSUE TITLE
GENERAL_INTERNAL_RETRYABLE(5000001L);

### ISSUE THREAD

**Issue by hakusai22** [apple/app-store-server-library-python#84]
Recently, there have been a lot of GENERAL_INTERNAL_RETRYABLE(5000001L) exceptions in the company's production environment. See the document https://developer.apple.com/documentation/appstoreserverapi/generalinternalretryableerror. I still don't understand why this exception occurs. I can only retry the request in the future.

**Comment by izanger** [comment]
If you receive these errors, it's recommended you try again a short while later, as you stated. I also encourage you to submit a report through Feedback Assistant. Include as much information as you can so we can investigate the issue, including the full error response you received and all headers.

https://feedbackassistant.apple.com
