### ISSUE TITLE
Allow more recent versions of cattrs

### ISSUE THREAD

**Issue by Tenzer** [apple/app-store-server-library-python#97]
This library current depends on cattrs version 23.1.2 specifically:
https://github.com/apple/app-store-server-library-python/blob/e746f5dcdca9347819a23f6e6254e97a3085e51f/setup.py#L18

Is there any good reason to not set that as the minimum version, and allow more recent versions of that library to be installed, like what is done with attrs?

It means we are stuck on an old version of cattrs in our code base where we also have app-store-server-library installed.

**Comment by alexanderjordanbaker** [comment]
Sure, @Tenzer, let me adjust some of these dependencies to be more open

**Comment by alexanderjordanbaker** [comment]
Resolved in https://github.com/apple/app-store-server-library-python/pull/101

**Comment by Tenzer** [comment]
Thank you!
